# Exercise 1 

In this exercise, we will work with the `spam.csv` data file. This file contains text and a label attached to each text. The goal is to clean the text data and then build classifcation models. 

### Exercise 1(a) (2 points)

Load the `pandas` and `numpy` libraries.

In [1]:
import pandas as pd
import numpy as np

### Exercise 1(b) (2 points)

Read the `csv` file and create a data-frame called `spam_df`.

In [2]:
spam_df = pd.read_csv("spam.csv")
spam_df.head()

  label                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

### Exercise 1(c) (2 points)

Using the `string` library, remove all the punctuation of the `text` column.

In [3]:
import string 

spam_df["text_clean"] = spam_df["text"].str.replace(f"[{string.punctuation}]", "", regex=True)
spam_df.head()

,label,text,text_clean
0,ham,"Go until jurong point, crazy.. Available only ...",Go until jurong point crazy Available only in ...
1,ham,Ok lar... Joking wif u oni...,Ok lar Joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...,U dun say so early hor U c already then say
4,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...

### Exercise 1(d) (10 points)

Using the `nltk` library, remove stopwords and pronouns from `text_clean` and store in another column called `'text_clean_1'`.

In [4]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stop_words = set(stopwords.words('english'))
pronouns = ['i', 'he', 'she', 'it', 'they', 'we', 'him', 'her', 'his', 'their', 'our', 'u', 'ur', 'im', 'dont', '2', 'ill', '4']

def clean_text(text):

    # Tokenize the text
    tokens = word_tokenize(text.lower())

    # Remove unwanted words
    tokens = [word for word in tokens if word not in stop_words and word not in pronouns]

    # Replacing words
    tokens = [word.replace('txt', 'text') for word in tokens]

    return ' '.join(tokens)

spam_df['text_clean_1'] = spam_df['text_clean'].apply(clean_text)
spam_df.head()

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/oscarm524/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /home/oscarm524/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

,label,text,text_clean,text_clean_1
0,ham,"Go until jurong point, crazy.. Available only ...",Go until jurong point crazy Available only in ...,go jurong point crazy available bugis n great ...
1,ham,Ok lar... Joking wif u oni...,Ok lar Joking wif u oni,ok lar joking wif oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,free entry wkly comp win fa cup final tkts 21s...
3,ham,U dun say so early hor... U c already then say...,U dun say so early hor U c already then say,dun say early hor c already say
4,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,nah think goes usf lives around though

### Exercise 1(e) (10 points)

Perform Lemmatization of `text_clean_1` and store the results in another column called `text_clean_2` in the `spam_df` data frame.

In [5]:
from nltk.corpus import wordnet
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

# Download necessary NLTK resources
nltk.download('wordnet')
nltk.download("averaged_perceptron_tagger")

# Initialize the lemmatizer
lemmatizer = WordNetLemmatizer()

# Function to get the part of speech tag for lemmatization
def get_wordnet_pos(word):
    tag = nltk.pos_tag([word])[0][1][0].upper()
    tag_dict = {"J": wordnet.ADJ,
                "N": wordnet.NOUN,
                "V": wordnet.VERB,
                "R": wordnet.ADV}
    return tag_dict.get(tag, wordnet.NOUN)

# Function to lemmatize text
def lemmatize_text(text):
    words = word_tokenize(text)
    lemmatized_words = [lemmatizer.lemmatize(word, get_wordnet_pos(word)) for word in words]
    return ' '.join(lemmatized_words)

# Apply the function to lemmatize the text
spam_df['text_clean_2'] = spam_df['text_clean_1'].apply(lemmatize_text)
spam_df.head()

[nltk_data] Downloading package wordnet to
[nltk_data]     /home/oscarm524/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/oscarm524/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

,label,text,text_clean,text_clean_1,text_clean_2
0,ham,"Go until jurong point, crazy.. Available only ...",Go until jurong point crazy Available only in ...,go jurong point crazy available bugis n great ...,go jurong point crazy available bugis n great ...
1,ham,Ok lar... Joking wif u oni...,Ok lar Joking wif u oni,ok lar joking wif oni,ok lar joking wif oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,free entry wkly comp win fa cup final tkts 21s...,free entry wkly comp win fa cup final tkts 21s...
3,ham,U dun say so early hor... U c already then say...,U dun say so early hor U c already then say,dun say early hor c already say,dun say early hor c already say
4,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,nah think goes usf lives around though,nah think go usf life around though

### Exercise 1(f) (5 points)

Based on the results from part 1(f), we see digits in some of the text in `text_clean_2`. Remove all the digits from `text_clean_2` and store the results in another column `text_clean_3` in the `spam_df` data frame.

In [6]:
import re

# Function to remove numbers
def remove_numbers(text):
    return re.sub(r'\d+', '', text)

# Apply the function to remove numbers from the cleaned text
spam_df['text_clean_3'] = spam_df['text_clean_2'].apply(remove_numbers)
spam_df.head()

,label,text,text_clean,text_clean_1,text_clean_2,text_clean_3
0,ham,"Go until jurong point, crazy.. Available only ...",Go until jurong point crazy Available only in ...,go jurong point crazy available bugis n great ...,go jurong point crazy available bugis n great ...,go jurong point crazy available bugis n great ...
1,ham,Ok lar... Joking wif u oni...,Ok lar Joking wif u oni,ok lar joking wif oni,ok lar joking wif oni,ok lar joking wif oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,free entry wkly comp win fa cup final tkts 21s...,free entry wkly comp win fa cup final tkts 21s...,free entry wkly comp win fa cup final tkts st ...
3,ham,U dun say so early hor... U c already then say...,U dun say so early hor U c already then say,dun say early hor c already say,dun say early hor c already say,dun say early hor c already say
4,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,nah think goes usf lives around though,nah think go usf life around though,nah think go usf life around though

### Exercise 1(g) (5 points)

Generate topic features using BERT embeddings on `text_clean_3`.

In [7]:
import matplotlib.pyplot as plt
import seaborn as sns

from sentence_transformers import SentenceTransformer
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

print("Loading BERT model...")
bert_model = SentenceTransformer('all-MiniLM-L6-v2')
print("BERT model loaded.")

# Generating the embeddings for the cleaned text
print("Generating embeddings...")
embeddings = bert_model.encode(spam_df['text_clean_3'].tolist(),
                               show_progress_bar=True, 
                               batch_size=32)
print("Embeddings generated.")
print(f"Embeddings shape: {embeddings.shape}")
print(f"Each document is represented by a {embeddings.shape[1]}-dimensional vector")

/home/oscarm524/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
/home/oscarm524/.local/lib/python3.10/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange
2026-10-22 19:35:35.845148: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-10-22 19:35:36.148910: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX512F AVX512_VNNI AVX512_BF16, in other operations, rebuild TensorFlow with the appropriate compiler flags.

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

Loading BERT model...
BERT model loaded.
Generating embeddings...

Batches:   0%|          | 0/175 [00:00<?, ?it/s]

Embeddings generated.
Embeddings shape: (5572, 384)
Each document is represented by a 384-dimensional vector

### Exercise 1(h) (5 points)

Apply the K-Means clustering algorithm to the bert embedding generated in the previous step.

1. Set the number of clusters to k=3.

2. Assign the cluster labels to a new column in `spam_df` called `'kmeans_cluster_label'`.

3. Generate new features by computing the distance of each document to the centroid of each of the k=3 clusters. Store these distances in a NumPy array called `X_kmeans_features`.

In [8]:
from sklearn.preprocessing import normalize

# Normalizing the embeddings
embeddings_normalized = normalize(embeddings)

# Apply KMeans clustering on the normalized embeddings
num_clusters = 3
kmeans = KMeans(n_clusters=num_clusters, n_init=20, random_state=42)
kmeans.fit(embeddings_normalized)

# Storing the cluster labels
spam_df['cluster'] = kmeans.labels_

# Compute the distance of each point to its assigned cluster center
X_kmeans_features = kmeans.transform(embeddings_normalized)

In [15]:
X_kmeans_features

array([[0.9111384 , 0.9414628 , 0.87042344],
       [0.91721344, 1.0041541 , 0.8659455 ],
       [0.93025416, 0.81574565, 0.8897186 ],
       ...,
       [0.9205432 , 0.99934685, 0.8821379 ],
       [0.9111099 , 0.9275718 , 0.9328345 ],
       [0.90503186, 1.0180368 , 0.9317566 ]], dtype=float32)

In [12]:
spam_df.head()

,label,text,text_clean,text_clean_1,text_clean_2,text_clean_3,cluster
0,ham,"Go until jurong point, crazy.. Available only ...",Go until jurong point crazy Available only in ...,go jurong point crazy available bugis n great ...,go jurong point crazy available bugis n great ...,go jurong point crazy available bugis n great ...,2
1,ham,Ok lar... Joking wif u oni...,Ok lar Joking wif u oni,ok lar joking wif oni,ok lar joking wif oni,ok lar joking wif oni,2
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,free entry wkly comp win fa cup final tkts 21s...,free entry wkly comp win fa cup final tkts 21s...,free entry wkly comp win fa cup final tkts st ...,1
3,ham,U dun say so early hor... U c already then say...,U dun say so early hor U c already then say,dun say early hor c already say,dun say early hor c already say,dun say early hor c already say,2
4,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,nah think goes usf lives around though,nah think go usf life around though,nah think go usf life around though,0

### Exercise 1(i) (5 points)

Hierarchical clustering is a type of density-based grouping used to organize documents based on similarity.

1. Apply Agglomerative Hierarchical Clustering to the L2​-normalized BERT embeddings (bert_embeddings) with k=3 clusters, using the `'ward'` linkage method.

2. Store the resulting cluster assignments in a new column called `'bert_hierarchical_label'` in `spam_df`.

3. Generate new features by computing the distance of each document to the centroid of each of the k=3 clusters. Store these distances in a NumPy array called `X_hierarchical_features`.

In [14]:
from sklearn.cluster import AgglomerativeClustering

# Apply Agglomerative Clustering on the normalized embeddings
num_clusters = 3
agg_clustering = AgglomerativeClustering(n_clusters=num_clusters, linkage="ward")
spam_df['bert_hierarchical_label'] = agg_clustering.fit_predict(embeddings_normalized)
print(spam_df.head())

  label                                               text  \
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

                                          text_clean  \
0  Go until jurong point crazy Available only in ...
1                            Ok lar Joking wif u oni
2  Free entry in 2 a wkly comp to win FA Cup fina...
3        U dun say so early hor U c already then say
4  Nah I dont think he goes to usf he lives aroun...

                                        text_clean_1  \
0  go jurong point crazy available bugis n great ...
1                              ok lar joking wif oni
2  free entry wkly comp win fa cup final tkts 21s...
3                    dun say early hor c already say
4             nah think goes usf lives around though

                                        text_clean_2  \
0  go jurong point crazy available bugis n great ...
1                              ok lar joking wif oni
2  free entry wkly comp win fa cup final tkts 21s...
3                    dun say early hor c already say
4                nah think go usf life around though

                                        text_clean_3  cluster  \
0  go jurong point crazy available bugis n great ...        2
1                              ok lar joking wif oni        2
2  free entry wkly comp win fa cup final tkts st ...        1
3                    dun say early hor c already say        2
4                nah think go usf life around though        0

   bert_hierarchical_label
0                        0
1                        0
2                        2
3                        0
4                        0

In [20]:
from sklearn.metrics.pairwise import euclidean_distances

# Compute the centroids manually
centroids = []
for i in range(num_clusters):
    centroids.append(embeddings_normalized[spam_df['cluster'] == i].mean(axis=0))
centroids = np.array(centroids)

# Compute distances to the centroids
X_hierarchical_features = euclidean_distances(embeddings_normalized, centroids)

In [21]:
X_hierarchical_features

array([[0.9111384 , 0.9414628 , 0.87042344],
       [0.91721344, 1.0041541 , 0.8659455 ],
       [0.93025416, 0.8157456 , 0.8897186 ],
       ...,
       [0.9205432 , 0.99934685, 0.8821379 ],
       [0.9111099 , 0.9275718 , 0.9328345 ],
       [0.90503186, 1.0180368 , 0.9317566 ]], dtype=float32)

### Exercise 1(j) (10 points)

Train and evaluate six `LogisticRegression` models as follows:

- Using `kmeans` features as input.
- Using `hierarchical` features as input.
- Using bert embedding features as input.
- Combining `kmeans` + bert embeddings features as input.
- Combining `hierarchical` + bert embeddings features as input.
- Combining `kmeans` + `hierarchical` + bert embeddings features as input.

Evaluate the six models over a five-fold cross validation strategy.

In [26]:
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

y = spam_df['label'].map({'ham': 0, 'spam': 1})
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# First input
X_kmeans = X_kmeans_features

# Second input
X_hierarchical = X_hierarchical_features

# Third input
X_third = embeddings

# Fourth input
X_fourth = np.hstack([X_kmeans, embeddings])

# Fifth input 
X_fifth = np.hstack([X_hierarchical, embeddings])

# Sixth input
X_sixth = np.hstack([X_kmeans, X_hierarchical, embeddings])

print("Comparing classification performance of different input combinations")
print("="*60)

model = make_pipeline(StandardScaler(), LogisticRegression(random_state=42))

# Evaluate each feature set
feature_sets = {
    "First input": X_kmeans,
    "Second input": X_hierarchical,
    "Third input": X_third,
    "Fourth input": X_fourth,
    "Fifth input": X_fifth,
    "Sixth input": X_sixth
}

results = {}
for name, X in feature_sets.items():
    scores = cross_val_score(model, X, y, cv=skf, scoring='accuracy')
    results[name] = (scores.mean(), scores.std())
    print(f"{name}: Mean accuracy = {scores.mean():.4f}, Std = {scores.std():.4f}")

# Finding the best performing feature set
best_feature_set = max(results, key=lambda k: results[k][0])
print(f"Best performing feature set: {best_feature_set} with Mean accuracy = {results[best_feature_set][0]:.4f}, Std = {results[best_feature_set][1]:.4f}")

Comparing classification performance of different input combinations
============================================================
First input: Mean accuracy = 0.9282, Std = 0.0053
Second input: Mean accuracy = 0.9282, Std = 0.0053
Third input: Mean accuracy = 0.9725, Std = 0.0044
Fourth input: Mean accuracy = 0.9725, Std = 0.0044
Fifth input: Mean accuracy = 0.9725, Std = 0.0044
Sixth input: Mean accuracy = 0.9724, Std = 0.0044
Best performing feature set: Third input with Mean accuracy = 0.9725, Std = 0.0044